### ISSUE TITLE
password dans le code ...

### ISSUE THREAD

**Issue by sylvek** [zaraki673/MyDomoHome.eu#1]
https://github.com/zaraki673/MyDomoHome.eu/blob/ef6dd8d07fcbf3345409653f8e50df92bf69bce8/Domoticz/Script/Veolia/veolia.py#L27

**Comment by zaraki673** [comment]
😱 
Bien vu merci beaucoup !!!!



De : Sylvain M.
Envoyé le :vendredi 29 décembre 2017 08:05
À : zaraki673/MyDomoHome.eu
Cc : Subscribed
Objet :[zaraki673/MyDomoHome.eu] password dans le code ... (#1)

https://github.com/zaraki673/MyDomoHome.eu/blob/ef6dd8d07fcbf3345409653f8e50df92bf69bce8/Domoticz/Script/Veolia/veolia.py#L27
